### ISSUE TITLE
Supervisor fails to download application

### ISSUE THREAD

**Issue by nazrhom** [balena-os/balena-supervisor#1084]
Supervisor version: 9.15.7

Ran into this on support. A user had just added another device to their application and the supervisor ended up stuck on the following error
```
Sep 09 20:59:19 748f535 resin-supervisor[1480]: Applying target state
Sep 09 20:59:20 748f535 resin-supervisor[1480]: Event: Docker image download {"image":{"name":"registry2.balena-cloud.com/v2/12cfb3678e770eb940952cfe9b132257@sha256:d24174a3de373c1565f96ec4afa56a33049f>
Sep 09 21:00:37 748f535 resin-supervisor[1480]: Event: Image download error {"error":{"message":"(HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/12cfb3678e770eb940952cfe9b1>
Sep 09 21:00:38 748f535 resin-supervisor[1480]: Scheduling another update attempt due to failure:  16000 { t
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at t.<anonymous> (/usr/src/app/dist/app.js:584:36600)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at /usr/src/app/dist/app.js:584:35765
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at Object.next (/usr/src/app/dist/app.js:584:35870)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at /usr/src/app/dist/app.js:584:34783
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at new Promise (<anonymous>)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at o (/usr/src/app/dist/app.js:584:34560)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at t.triggerFetch (/usr/src/app/dist/app.js:584:36260)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at /usr/src/app/dist/app.js:576:57144
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at c (/usr/src/app/dist/app.js:9:74428)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at Holder$2._callFunction (eval at d (/usr/src/app/dist/app.js:293:153468), <anonymous>:14:44)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at Holder$2.checkFulfillment (eval at d (/usr/src/app/dist/app.js:293:153468), <anonymous>:29:30)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at A.eval (eval at f (/usr/src/app/dist/app.js:293:149118), <anonymous>:6:20)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at A._settlePromise (/usr/src/app/dist/app.js:293:114985)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at A._settlePromise0 (/usr/src/app/dist/app.js:293:115646)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at A._settlePromises (/usr/src/app/dist/app.js:293:116998)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at A._fulfill (/usr/src/app/dist/app.js:293:116016)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at A._resolveCallback (/usr/src/app/dist/app.js:293:112895)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at A._settlePromiseFromHandler (/usr/src/app/dist/app.js:293:114301)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at A._settlePromise (/usr/src/app/dist/app.js:293:114947)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at A._settlePromise0 (/usr/src/app/dist/app.js:293:115646)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at A._settlePromises (/usr/src/app/dist/app.js:293:116998)
Sep 09 21:00:38 748f535 resin-supervisor[1480]:     at A._fulfill (/usr/src/app/dist/app.js:293:116016) message: '', name: 't' }
Sep 09 21:00:38 748f535 resin-supervisor[1480]: Apply error t
```

After restarting the supervisor the download went through successfully

**Comment by DanielGnzlzVll** [comment]
> After restarting the supervisor the download went through successfully

With other device i was try reboot and this did not work

**Comment by DanielGnzlzVll** [comment]
any update?

**Comment by CameronDiver** [comment]
Unfortunately not, we've not been able to reproduce or identify how this would happen. If the supervisor attempts to download and image without an authentication token or an incorrect one, it would get a 404, and that's the only reasonable explanation IMO. I would've that we would see this a lot more often though, so it certainly seems very dependent on other factors. Getting a reproduction of this would be fantastic, so if you hit it again please do let us know.

**Comment by pdcastro** [comment]
I managed to recover a device seemingly affected by this issue:
```
Oct 09 17:17:49 QA1_device4-82caa4dd resin-supervisor[19498]: delta([provisioning] registry2.balena-cloud.com/v2/c7b65314f35fdb01a9453bff0d636622@sha256:04b97e6be4bbb96ed5859ce0a7b0b5a2e497a41ffc57d666f423ba57372412bb): Delta failed with Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/affa64f46bc5b07a80d9acc2d4b915ff:delta-df1470b9e4ff760b: No such image: registry2.balena-cloud.com/v2/affa64f46bc5b07a80d9acc2d4b915ff:delta-df1470b9e4ff760b
Oct 09 17:17:49 QA1_device4-82caa4dd resin-supervisor[19498]: Event: Image download error {"error":{"message":"(HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/affa64f46bc5b07a80d9acc2d4b915ff:delta-df1470b9e4ff760b: No such image: registry2.balena-cloud.com/v2/affa64f46bc5b07a80d9acc2d4b915ff:delta-df1470b9e4ff760b ","stack":"Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/affa64f46bc5b07a80d9acc2d4b915ff:delta-df1470b9e4ff760b: No such image: registry2.balena-cloud.com/v2/affa64f46bc5b07a80d9acc2d4b915ff:delta-df1470b9e4ff760b \n    at /usr/src/app/dist/app.js:576:112868\n    at /usr/src/app/dist/app.js:576:112831\n    at m.buildPayload (/usr/src/app/dist/app.js:576:112841)\n    at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:576:112341)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1125:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"image":{"name":"registry2.balena-cloud.com/v2/affa64f46bc5b07a80d9acc2d4b915ff@sha256:4232d2accdefe38fd6f5c1519ea6182859ecafab2ff1b9de6aa2d8ef50236a03","appId":1344734,"serviceId":163233,"serviceName":"provisioning","imageId":1572352,"releaseId":1098322,"dependent":0,"dockerImageId":null}}
Oct 09 17:17:49 QA1_device4-82caa4dd resin-supervisor[19498]: delta([mqtt] registry2.balena-cloud.com/v2/c7b65314f35fdb01a9453bff0d636622@sha256:04b97e6be4bbb96ed5859ce0a7b0b5a2e497a41ffc57d666f423ba57372412bb): Delta failed with Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/c27658fb71e037fb8e25ddfb989a6c06:delta-f87b76500103ad34: No such image: registry2.balena-cloud.com/v2/c27658fb71e037fb8e25ddfb989a6c06:delta-f87b76500103ad34
Oct 09 17:17:49 QA1_device4-82caa4dd resin-supervisor[19498]: Event: Image download error {"error":{"message":"(HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/c27658fb71e037fb8e25ddfb989a6c06:delta-f87b76500103ad34: No such image: registry2.balena-cloud.com/v2/c27658fb71e037fb8e25ddfb989a6c06:delta-f87b76500103ad34 ","stack":"Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/c27658fb71e037fb8e25ddfb989a6c06:delta-f87b76500103ad34: No such image: registry2.balena-cloud.com/v2/c27658fb71e037fb8e25ddfb989a6c06:delta-f87b76500103ad34 \n    at /usr/src/app/dist/app.js:576:112868\n    at /usr/src/app/dist/app.js:576:112831\n    at m.buildPayload (/usr/src/app/dist/app.js:576:112841)\n    at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:576:112341)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1125:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"image":{"name":"registry2.balena-cloud.com/v2/c27658fb71e037fb8e25ddfb989a6c06@sha256:6eade50337da481c6a2b65e6b885685dce27751096f8c77eb0e25b4ecd6fe44b","appId":1344734,"serviceId":325815,"serviceName":"mqtt","imageId":1572354,"releaseId":1098322,"dependent":0,"dockerImageId":null}}
```
... by manually running some pull commands:
```
$ balena login registry2.balena-cloud.com
$ balena pull registry2.balena-cloud.com/v2/affa64f46bc5b07a80d9acc2d4b915ff
$ balena pull registry2.balena-cloud.com/v2/affa64f46bc5b07a80d9acc2d4b915ff:delta-df1470b9e4ff760b
$ balena pull registry2.balena-cloud.com/v2/c27658fb71e037fb8e25ddfb989a6c06:delta-f87b76500103ad34
$ balena pull registry2.balena-cloud.com/v2/c7b65314f35fdb01a9453bff0d636622@sha256:04b97e6be4bbb96ed5859ce0a7b0b5a2e497a41ffc57d666f423ba57372412bb
```
And then restarting the supervisor (restarting it before the manual pull did not help). Not quite sure what to conclude though: have I simply bypassed the need to download deltas by manually downloading the full image?

**Comment by pdcastro** [comment]
Another occurrence (on Balena Fin (CM3), balenaOS 2.38.0+rev1.prod, supervisor 9.15.7):
```
Oct 11 17:35:04 61c13782 resin-supervisor[31571]: delta([provisioning] registry2.balena-cloud.com/v2/c7b65314f35fdb01a9453bff0d636622@sha256:04b97e6be4bbb96ed5859ce0a7b0b5a2e497a41ffc57d666f423ba57372412bb): Delta failed with Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/52ed4085d62e9ed6195c35baaea84982:delta-b3619586592b618e: No such image: registry2.balena-cloud.com/v2/52ed4085d62e9ed6195c35baaea84982:delta-b3619586592b618e
Oct 11 17:35:04 61c13782 resin-supervisor[31571]: Event: Image download error {"error":{"message":"(HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/52ed4085d62e9ed6195c35baaea84982:delta-b3619586592b618e: No such image: registry2.balena-cloud.com/v2/52ed4085d62e9ed6195c35baaea84982:delta-b3619586592b618e ","stack":"Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/52ed4085d62e9ed6195c35baaea84982:delta-b3619586592b618e: No such image: registry2.balena-cloud.com/v2/52ed4085d62e9ed6195c35baaea84982:delta-b3619586592b618e \n    at /usr/src/app/dist/app.js:576:112868\n    at /usr/src/app/dist/app.js:576:112831\n    at m.buildPayload (/usr/src/app/dist/app.js:576:112841)\n    at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:576:112341)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1125:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"image":{"name":"registry2.balena-cloud.com/v2/52ed4085d62e9ed6195c35baaea84982@sha256:4ad5c9cf8e9a3971947596afdc3e72219d775c1db3f7a929fda52ad8bd511007","appId":1344734,"serviceId":163233,"serviceName":"provisioning","imageId":1580896,"releaseId":1102050,"dependent":0,"dockerImageId":null}}
Oct 11 17:35:04 61c13782 resin-supervisor[31571]: delta([mqtt] registry2.balena-cloud.com/v2/c7b65314f35fdb01a9453bff0d636622@sha256:04b97e6be4bbb96ed5859ce0a7b0b5a2e497a41ffc57d666f423ba57372412bb): Delta failed with Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/79b5e33b3aec5a1a2f86e4850830a166:delta-4519f0d45951b1eb: No such image: registry2.balena-cloud.com/v2/79b5e33b3aec5a1a2f86e4850830a166:delta-4519f0d45951b1eb
Oct 11 17:35:04 61c13782 resin-supervisor[31571]: Event: Image download error {"error":{"message":"(HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/79b5e33b3aec5a1a2f86e4850830a166:delta-4519f0d45951b1eb: No such image: registry2.balena-cloud.com/v2/79b5e33b3aec5a1a2f86e4850830a166:delta-4519f0d45951b1eb ","stack":"Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/79b5e33b3aec5a1a2f86e4850830a166:delta-4519f0d45951b1eb: No such image: registry2.balena-cloud.com/v2/79b5e33b3aec5a1a2f86e4850830a166:delta-4519f0d45951b1eb \n    at /usr/src/app/dist/app.js:576:112868\n    at /usr/src/app/dist/app.js:576:112831\n    at m.buildPayload (/usr/src/app/dist/app.js:576:112841)\n    at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:576:112341)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1125:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"image":{"name":"registry2.balena-cloud.com/v2/79b5e33b3aec5a1a2f86e4850830a166@sha256:88f439ea841b4feac1dd2c01cc6894f47a98b5384dfe8d478e5002f65402f718","appId":1344734,"serviceId":325815,"serviceName":"mqtt","imageId":1580898,"releaseId":1102050,"dependent":0,"dockerImageId":null}}
Oct 11 17:35:05 61c13782 resin-supervisor[31571]: Replacing container for service provisioning because of config changes:
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:   Non-array fields:  {"added":{},"deleted":{"entrypoint":{},"environment":{},"labels":{}},"updated":{"image":"registry2.balena-cloud.com/v2/52ed4085d62e9ed6195c35baaea84982@sha256:4ad5c9cf8e9a3971947596afdc3e72219d775c1db3f7a929fda52ad8bd511007","stopSignal":"SIGTERM","workingDir":"","healthcheck":{"interval":60000000000}}}
Oct 11 17:35:05 61c13782 resin-supervisor[31571]: Replacing container for service provisioning because of config changes:
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:   Non-array fields:  {"added":{},"deleted":{"entrypoint":{},"environment":{},"labels":{}},"updated":{"image":"registry2.balena-cloud.com/v2/52ed4085d62e9ed6195c35baaea84982@sha256:4ad5c9cf8e9a3971947596afdc3e72219d775c1db3f7a929fda52ad8bd511007","stopSignal":"SIGTERM","workingDir":"","healthcheck":{"interval":60000000000}}}
Oct 11 17:35:05 61c13782 resin-supervisor[31571]: Replacing container for service provisioning because of config changes:
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:   Non-array fields:  {"added":{},"deleted":{"entrypoint":{},"environment":{},"labels":{}},"updated":{"image":"registry2.balena-cloud.com/v2/52ed4085d62e9ed6195c35baaea84982@sha256:4ad5c9cf8e9a3971947596afdc3e72219d775c1db3f7a929fda52ad8bd511007","stopSignal":"SIGTERM","workingDir":"","healthcheck":{"interval":60000000000}}}
Oct 11 17:35:05 61c13782 resin-supervisor[31571]: Scheduling another update attempt due to failure:  256000 { t
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at t.<anonymous> (/usr/src/app/dist/app.js:584:36600)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at /usr/src/app/dist/app.js:584:35765
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at Object.next (/usr/src/app/dist/app.js:584:35870)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at /usr/src/app/dist/app.js:584:34783
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at new Promise (<anonymous>)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at o (/usr/src/app/dist/app.js:584:34560)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at t.triggerFetch (/usr/src/app/dist/app.js:584:36260)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at /usr/src/app/dist/app.js:576:57144
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at c (/usr/src/app/dist/app.js:9:74428)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at Holder$2._callFunction (eval at d (/usr/src/app/dist/app.js:293:153468), <anonymous>:14:44)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at Holder$2.checkFulfillment (eval at d (/usr/src/app/dist/app.js:293:153468), <anonymous>:29:30)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at A.eval (eval at f (/usr/src/app/dist/app.js:293:149118), <anonymous>:6:20)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at A._settlePromise (/usr/src/app/dist/app.js:293:114985)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at A._settlePromise0 (/usr/src/app/dist/app.js:293:115646)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at A._settlePromises (/usr/src/app/dist/app.js:293:116998)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at A._fulfill (/usr/src/app/dist/app.js:293:116016)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at A._resolveCallback (/usr/src/app/dist/app.js:293:112895)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at A._settlePromiseFromHandler (/usr/src/app/dist/app.js:293:114301)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at A._settlePromise (/usr/src/app/dist/app.js:293:114947)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at A._settlePromise0 (/usr/src/app/dist/app.js:293:115646)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at A._settlePromises (/usr/src/app/dist/app.js:293:116998)
Oct 11 17:35:05 61c13782 resin-supervisor[31571]:     at A._fulfill (/usr/src/app/dist/app.js:293:116016) message: '', name: 't' }
Oct 11 17:35:05 61c13782 resin-supervisor[31571]: Apply error t
Oct 11 17:35:19 61c13782 resin-supervisor[31571]: Supervisor API: GET /v1/healthy 200 - 20.433 ms
```
Again fixed with manual "balena pull" (merely restarting the supervisor was not sufficient):
```
$ systemctl stop resin-supervisor
$ balena login registry2.balena-cloud.com
$ balena pull registry2.balena-cloud.com/v2/c7b65314f35fdb01a9453bff0d636622@sha256:04b97e6be4bbb96ed5859ce0a7b0b5a2e497a41ffc57d666f423ba57372412bb
$ systemctl start resin-supervisor
$ balena logout registry2.balena-cloud.com
```

**Comment by pdcastro** [comment]
Details from another manually fixed device / investigation.
This time, the device was running balenaOS 2.29.0+rev1.prod, supervisor 9.0.1.

Before the fix:
```
root@QA1_device1-143a9978:~# balena images -a
REPOSITORY                                                       TAG                      IMAGE ID            CREATED             SIZE
registry2.balena-cloud.com/v2/82de77049e9d0a39c2448d1d95db2848   delta-14508b6ae66b84fc   595e78f36597        2 hours ago         463MB
registry2.balena-cloud.com/v2/efbace57e741f9788d8f59a317ecd343   delta-2157332bdde8dd98   7491c1c34034        2 hours ago         426MB
registry2.balena-cloud.com/v2/67d010c43e46ca5f999da242d456cb07   delta-d15a7bbe17c279af   533395dc7d12        3 hours ago         353MB
registry2.balena-cloud.com/v2/2ae10433e104be686a82047a399a3247   delta-2b290d6569c96a58   515a8c979c08        3 hours ago         365MB
registry2.balena-cloud.com/v2/fb2eb66146c570d4bd5854c48b6770d2   delta-ad61104e1681a2da   70d8fa7d88f9        4 hours ago         335MB
registry2.balena-cloud.com/v2/6e9f7f5cb6d876b60d021b2a9a8e9f8e   delta-27c156048813dabb   7f9ce2033af6        4 hours ago         291MB
registry2.balena-cloud.com/v2/f5534a6d2463894ea1b3930cdedb2468   delta-9bfd75a6772a36e5   8a55cb584975        4 hours ago         298MB
balenalib/raspberrypi3-alpine                                    latest                   5c5574887711        2 weeks ago         38MB
balena/armv7hf-supervisor                                        v9.0.1                   835f656b8cea        10 months ago       53.5MB

$ journalctl -au resin-supervisor
...
Oct 21 19:04:27 QA1_device1-143a9978 balenad[7852]: [2019-10-21T19:04:27.831Z] delta(registry2.balena-cloud.com/v2/fb2eb66146c570d4bd5854c48b6770d2@sha256:57c8d309526801034cbaff1e2a82b86f947ee1a6e46b70b3a69d52ebbb0b89d5):
  Delta failed with: Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/6e223dc6de7fbd20bf64a34092084474:delta-acc1b85325b9d014:
  No such image: registry2.balena-cloud.com/v2/6e223dc6de7fbd20bf64a34092084474:delta-acc1b85325b9d014

Oct 21 19:04:27 QA1_device1-143a9978 balenad[7852]: [2019-10-21T19:04:27.852Z] Event: Image download error {"error":{"message":"(HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/6e223dc6de7fbd20bf64a34092084474:delta-acc1b85325b9d014: 
  No such image: registry2.balena-cloud.com/v2/6e223dc6de7fbd20bf64a34092084474:delta-acc1b85325b9d014 ","stack":"Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/6e223dc6de7fbd20bf64a34092084474:delta-acc1b85325b9d014:
  No such image: registry2.balena-cloud.com/v2/6e223dc6de7fbd20bf64a34092084474:delta-acc1b85325b9d014 \n
    at /usr/src/app/dist/app.js:583:105903\n
    at /usr/src/app/dist/app.js:583:105866\n
    at m.buildPayload (/usr/src/app/dist/app.js:583:105876)\n
    at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:583:105376)\n
    at emitNone (events.js:91:20)\n
    at IncomingMessage.emit (events.js:185:7)\n
    at endReadableNT (_stream_readable.js:974:12)\n
    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n
    at process._tickCallback (internal/process/next_tick.js:104:9)"},"image":{"name":"registry2.balena-cloud.com/v2/6e223dc6de7fbd20bf64a34092084474@sha256:4ffe4ee558690034b321ce09e53e73d1e79b24bcae43f4a8a34bddfdb903673a","appId":1344734,"serviceId":203964,"serviceName":"balena_tags","imageId":1607811,"releaseId":1113761,"dependent":0,"dockerImageId":null}}
```

The device was fixed by running:
```
systemctl stop resin-supervisor
# login details obtained from /mnt/boot/config.json
balena login registry2.balena-cloud.com
balena pull registry2.balena-cloud.com/v2/6e223dc6de7fbd20bf64a34092084474
balena logout registry2.balena-cloud.com
systemctl start resin-supervisor
```

After the fix, image `registry2.balena-cloud.com/v2/6e223dc6de7fbd20bf64a34092084474` was listed with `balena images -a`, while image `registry2.balena-cloud.com/v2/fb2eb66146c570d4bd5854c48b6770d2:delta-ad61104e1681a2da` was no longer listed:
```
root@QA1_device1-143a9978:~# balena images -a
REPOSITORY                                                       TAG                      IMAGE ID            CREATED             SIZE
registry2.balena-cloud.com/v2/82de77049e9d0a39c2448d1d95db2848   delta-14508b6ae66b84fc   595e78f36597        3 hours ago         463MB
registry2.balena-cloud.com/v2/6e223dc6de7fbd20bf64a34092084474   latest                   44ef9c392e55        3 hours ago         335MB
registry2.balena-cloud.com/v2/efbace57e741f9788d8f59a317ecd343   delta-2157332bdde8dd98   7491c1c34034        3 hours ago         426MB
registry2.balena-cloud.com/v2/67d010c43e46ca5f999da242d456cb07   delta-d15a7bbe17c279af   533395dc7d12        4 hours ago         353MB
registry2.balena-cloud.com/v2/2ae10433e104be686a82047a399a3247   delta-2b290d6569c96a58   515a8c979c08        4 hours ago         365MB
registry2.balena-cloud.com/v2/6e9f7f5cb6d876b60d021b2a9a8e9f8e   delta-27c156048813dabb   7f9ce2033af6        5 hours ago         291MB
registry2.balena-cloud.com/v2/f5534a6d2463894ea1b3930cdedb2468   delta-9bfd75a6772a36e5   8a55cb584975        5 hours ago         298MB
balenalib/raspberrypi3-alpine                                    latest                   5c5574887711        2 weeks ago         38MB
balena/armv7hf-supervisor                                        v9.0.1                   835f656b8cea        10 months ago       53.5MB
```

A finding of interest (?) is that sha256 hash (repo digest) for one of the source images mentioned in the supervisor logs did not match the hash (repo digest) listed by `balena inspect` for one of the delta images:
```
root@QA1_device1-143a9978:~# balena inspect registry2.balena-cloud.com/v2/fb2eb66146c570d4bd5854c48b6770d2@sha256:57c8d309526801034cbaff1e2a82b86f947ee1a6e46b70b3a69d52ebbb0b89d5
[]
Error: No such object: registry2.balena-cloud.com/v2/fb2eb66146c570d4bd5854c48b6770d2@sha256:57c8d309526801034cbaff1e2a82b86f947ee1a6e46b70b3a69d52ebbb0b89d5

root@QA1_device1-143a9978:~# balena inspect registry2.balena-cloud.com/v2/fb2eb66146c570d4bd5854c48b6770d2:delta-ad61104e1681a2da
[
    {
        "Id": "sha256:70d8fa7d88f9a8347a705b0821cdef2cd3dd6215f47fda69586dbc66d819e7e7",
        "RepoTags": [
            "registry2.balena-cloud.com/v2/fb2eb66146c570d4bd5854c48b6770d2:delta-ad61104e1681a2da"
        ],
        "RepoDigests": [
            "registry2.balena-cloud.com/v2/fb2eb66146c570d4bd5854c48b6770d2@sha256:e1429fc43d16486461ef2514ff6e9d9ffcfc733ba8e1cc6e6e32a140b5f43b4d"
        ],
```
CC: @CameronDiver, @richbayliss

**Comment by roman-mazur** [comment]
It's most likely the backend problem (not having the necessary deltas and not providing full images instead when deltas are not available), not the supervisor's.

@pdcastro Thanks for the detailed steps - they are very helpful.

**Comment by roman-mazur** [comment]
For the future: instead of manual image pull we could simply disable deltas for the device and see how it works.

**Comment by CameronDiver** [comment]
I've just merged https://github.com/balena-io/balena-supervisor/pull/1234 which should help get a better error message for these situations, and let us know what exactly is going wrong.

**Comment by dfunckt** [comment]
When this happens please get engine logs -- the Supervisor will merely report what the engine says which will have already wrapped the error in a generic 404, which is useless.

I'll start first: I'm looking at a device just now that on the surface seems to face an identical issue (OS 2.43) with balena deltas. This is the earliest error in the chain of wrapped messages:

```
Attempting next endpoint for pull after error: failed to register layer: Error processing tar file(exit status 1): unexpected EOF
```

There is also at least one engine core dump which seems related but I was only able to catch its tail as the logs rotated.

**Comment by pipex** [comment]
I'm closing this as there has been no activity for a year. Image download issues are usually unrelated to the supervisor, which just passes the requests down to the engine/network.
