### ISSUE TITLE
Failure to validate IPAM network configuration

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-supervisor#1618]
The function for [validating](https://github.com/balena-io/balena-supervisor/blob/master/src/compose/network.ts#L211-L224) IPAM network configurations is not working correctly and is leading to undefined behavior. In the case we had seen releases were failing to start containers because the Supervisor was getting the following error:

```
Mar 06 01:01:34 69f6f22 resin-supervisor[7887]: [debug]   Attempting to create network {"name":"default","appId":1800203,"config":{"driver":"bridge","ipam":{"driver":"default","config":[{"subnet":"172.29.238.0/24"},{"subnet":"2001:3984:3989::/64"}],"options":{}},"enableIPv6":false,"internal":false,"labels":{},"options":{}}}
Mar 06 01:01:34 69f6f22 resin-supervisor[7887]: [debug]   Creating network:  {"name":"default","appId":1800203,"config":{"driver":"bridge","ipam":{"driver":"default","config":[{"subnet":"172.29.238.0/24"},{"subnet":"2001:3984:3989::/64"}],"options":{}},"enableIPv6":false,"internal":false,"labels":{},"options":{}}}
Mar 06 01:01:34 69f6f22 resin-supervisor[7887]: [error]   Scheduling another update attempt in 64000ms due to failure:  Error: Failed to apply state transition steps. network.create is not a function Steps:["start","createNetwork"]
Mar 06 01:01:34 69f6f22 resin-supervisor[7887]: [error]         at /usr/src/app/src/device-state.ts:1594:10
Mar 06 01:01:34 69f6f22 resin-supervisor[7887]: [error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
Mar 06 01:01:34 69f6f22 resin-supervisor[7887]: [error]   Device state apply error Error: Failed to apply state transition steps. network.create is not a function Steps:["start","createNetwork"]
Mar 06 01:01:34 69f6f22 resin-supervisor[7887]: [error]         at /usr/src/app/src/device-state.ts:1594:10
Mar 06 01:01:34 69f6f22 resin-supervisor[7887]: [error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Upon further investigation we saw that the release had an malformed IMAP configuration for the docker-compose file however, since the Supervisor failed to catch this invalid config it cause a variable to not be initialized as the correct type and creating the above error.

**Comment by 20k-ultra** [comment]
The string for looking up the config should not contain config and just be ipam.conf https://github.com/balena-io/balena-supervisor/blob/44e8134e02cd75491c4caad005d6392f5d66d41a/src/compose/network.ts#L217
