### ISSUE TITLE
Device state apply error SyntaxError: Unexpected token ] in JSON at position 35

### ISSUE THREAD

**Issue by minusplusminus** [balena-os/balena-supervisor#1654]
```
Apr 08 18:42:17 d78ac24 balenad[1806]: time="2021-04-08T18:42:17.143285158Z" level=info msg="shim balena-engine-containerd-shim started" address=/containerd-shim/bba97fecdef7c05bea43a90f7feb9df95f1f5102d1ba09669da05c4175394a20.sock debug=false pid=2798
Apr 08 18:42:18 d78ac24 balenad[1806]: time="2021-04-08T18:42:18.294811324Z" level=info msg="shim reaped" id=423ed9a94c6bd444d372546311ce8183163c144114bd40f46bb056dc7cd58e8a
Apr 08 18:42:18 d78ac24 balenad[1759]: time="2021-04-08T18:42:18.300697583Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [info]    Applying target state
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [info]    Applying target state
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]   Scheduling another update attempt in 60000ms due to failure:  SyntaxError: Unexpected token ] in JSON at position 35
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]   Scheduling another update attempt in 60000ms due to failure:  SyntaxError: Unexpected token ] in JSON at position 35
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]         at JSON.parse (<anonymous>)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at ConfigTxt.processConfigVarValue (/usr/src/app/dist/app.js:10:2484598)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at /usr/src/app/dist/app.js:10:2471854
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]         at JSON.parse (<anonymous>)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at ConfigTxt.processConfigVarValue (/usr/src/app/dist/app.js:10:2484598)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at /usr/src/app/dist/app.js:10:2471854
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at /usr/src/app/dist/app.js:2:101637
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at /usr/src/app/dist/app.js:2:54165
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at /usr/src/app/dist/app.js:2:101637
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at /usr/src/app/dist/app.js:2:54165
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at baseForOwn (/usr/src/app/dist/app.js:2:31078)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at Function.lodash.mapValues (/usr/src/app/dist/app.js:2:101564)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at /usr/src/app/dist/app.js:2:48605
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at arrayReduce (/usr/src/app/dist/app.js:2:10552)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at baseForOwn (/usr/src/app/dist/app.js:2:31078)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at Function.lodash.mapValues (/usr/src/app/dist/app.js:2:101564)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at /usr/src/app/dist/app.js:2:48605
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at arrayReduce (/usr/src/app/dist/app.js:2:10552)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at baseWrapperValue (/usr/src/app/dist/app.js:2:48541)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at LodashWrapper.lodash.toJSON.lodash.valueOf.lodash.value (/usr/src/app/dist/app.js:2:134507)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at baseWrapperValue (/usr/src/app/dist/app.js:2:48541)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at LodashWrapper.lodash.toJSON.lodash.valueOf.lodash.value (/usr/src/app/dist/app.js:2:134507)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at Object.exports.envToBootConfig (/usr/src/app/dist/app.js:10:2471890)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at bootConfigChangeRequired (/usr/src/app/dist/app.js:6:293022)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at changeRequired (/usr/src/app/dist/app.js:6:293880)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at Object.exports.getRequiredSteps (/usr/src/app/dist/app.js:6:299195)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at async fn (/usr/src/app/dist/app.js:6:7275)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at Object.exports.envToBootConfig (/usr/src/app/dist/app.js:10:2471890)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at bootConfigChangeRequired (/usr/src/app/dist/app.js:6:293022)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at changeRequired (/usr/src/app/dist/app.js:6:293880)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at Object.exports.getRequiredSteps (/usr/src/app/dist/app.js:6:299195)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at async fn (/usr/src/app/dist/app.js:6:7275)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]   Device state apply error SyntaxError: Unexpected token ] in JSON at position 35
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]         at JSON.parse (<anonymous>)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at ConfigTxt.processConfigVarValue (/usr/src/app/dist/app.js:10:2484598)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at /usr/src/app/dist/app.js:10:2471854
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at /usr/src/app/dist/app.js:2:101637
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at /usr/src/app/dist/app.js:2:54165
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at baseForOwn (/usr/src/app/dist/app.js:2:31078)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at Function.lodash.mapValues (/usr/src/app/dist/app.js:2:101564)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at /usr/src/app/dist/app.js:2:48605
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at arrayReduce (/usr/src/app/dist/app.js:2:10552)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at baseWrapperValue (/usr/src/app/dist/app.js:2:48541)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at LodashWrapper.lodash.toJSON.lodash.valueOf.lodash.value (/usr/src/app/dist/app.js:2:134507)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at Object.exports.envToBootConfig (/usr/src/app/dist/app.js:10:2471890)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]   Device state apply error SyntaxError: Unexpected token ] in JSON at position 35
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]         at JSON.parse (<anonymous>)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at ConfigTxt.processConfigVarValue (/usr/src/app/dist/app.js:10:2484598)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at /usr/src/app/dist/app.js:10:2471854
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at /usr/src/app/dist/app.js:2:101637
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at /usr/src/app/dist/app.js:2:54165
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at baseForOwn (/usr/src/app/dist/app.js:2:31078)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at Function.lodash.mapValues (/usr/src/app/dist/app.js:2:101564)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at /usr/src/app/dist/app.js:2:48605
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at arrayReduce (/usr/src/app/dist/app.js:2:10552)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at baseWrapperValue (/usr/src/app/dist/app.js:2:48541)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at LodashWrapper.lodash.toJSON.lodash.valueOf.lodash.value (/usr/src/app/dist/app.js:2:134507)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at Object.exports.envToBootConfig (/usr/src/app/dist/app.js:10:2471890)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at bootConfigChangeRequired (/usr/src/app/dist/app.js:6:293022)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at changeRequired (/usr/src/app/dist/app.js:6:293880)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at bootConfigChangeRequired (/usr/src/app/dist/app.js:6:293022)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at changeRequired (/usr/src/app/dist/app.js:6:293880)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at Object.exports.getRequiredSteps (/usr/src/app/dist/app.js:6:299195)
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]       at async fn (/usr/src/app/dist/app.js:6:7275)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at Object.exports.getRequiredSteps (/usr/src/app/dist/app.js:6:299195)
Apr 08 18:42:24 d78ac24 f6f44d8bb90c[1759]: [error]       at async fn (/usr/src/app/dist/app.js:6:7275)
```

**Comment by cywang117** [comment]
Hi @minusplusminus, 

Thanks for bringing this issue to our attention. Could you provide some additional context for this error please?
Some info that would help: device type, Supervisor version, balenaOS version.

Additionally, it looks like there could be invalid device config variable within your device's boot config file. Could you provide any custom device configuration variables you may have added? These should be reported on the dashboard, under Device Configuration.

Cheers,
Christina

**Comment by minusplusminus** [comment]
Hi sorry forgot to add.

- Rpi 4
- BalenaOS 2.73.1+rev1

Downloaded it yesterday and installed it. No changes. It gives the error in balena cloud on one specific application in my dashboard. When I moved the device to a newly made one there where no errors anymore. Tried is 2 times. Even downgraded to older versions and all got the same issue. Changed SD card,  which didn't solve the issue.

**Comment by cywang117** [comment]
@minusplusminus Thanks for the additional context. What is the Supervisor version for your application? Also, when you say you removed env vars, did you remove env vars for the application that was erroring?

My hypothesis is that this has to do with an improper env var format in your config file, which is located at `/mnt/boot/config.txt` for RPi models. If you haven't added any sensitive custom config vars, would you mind pushing the erroring application again to your RPi, running `cat /mnt/boot/config.txt` in a new Host OS terminal instance (launchable from the balenaCloud dashboard Device Summary page) and pasting the results?

**Comment by minusplusminus** [comment]
```
"i2c_arm=on","spi=on","audio=on", 
```

comma appeared.  Don't know why. So this could be the issue

**Comment by cywang117** [comment]
@minusplusminus Thanks for following up & closing the issue! You're right, the comma led to an error when calling JSON.parse. You can see the source of the bug you saw in your logs [here](https://github.com/balena-os/balena-supervisor/blob/master/src/config/backends/config-txt.ts#L138-L147). However, Supervisor can certainly do a better job of communicating the existence of malformed env vars, instead of throwing a cryptic error. I'll mention this issue in a running thread we have for patterns like these.

**Comment by minusplusminus** [comment]
Yes that would be nice. Woud save me a few hours  :) Thanks for the service

**Comment by cywang117** [comment]
Going to reopen the issue - looks like a straightforward change in the codebase.

**Comment by 20k-ultra** [comment]
@minusplusminus @cywang117 I'm thinking we modify all the [backends](https://github.com/balena-os/balena-supervisor/tree/master/src/config/backends) to log a message saying "Validating target {backend} configurations..." and then log if they pass or fail. 

```
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [info]    Applying target state
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [info]    Validating target config.txt configuration...
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [error]    Target config.txt configuration is invalid!
```

```
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [info]    Applying target state
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [info]    Validating target config.txt configuration...
Apr 08 18:42:24 d78ac24 resin-supervisor[2257]: [info]    Applying target config.txt configuration.
```

Due to the way the Supervisor applies target state we cannot make it continue on passed this issue. Device configurations are applied before application changes. Your device will loop this error until it is resolved.

**Comment by cywang117** [comment]
@20k-ultra Would the error cause the state apply loop to exit? New instances of polled target state would keep having instances of the invalid config vars, we'd need some kind of flag to ignore this when it comes in to prevent the state funnel from starting, if every other aspect of the target state is the same as the current state

**Comment by 20k-ultra** [comment]
That's what I'm saying. The current system will continue to keep trying to apply the configuration which would throw the exception. With the purposed change we will still get stuck in the loop but log that we detected an invalid configuration so the user can fix it. The Supervisor can't skip applying the configuration and apply the rest of the target state.

**Comment by cywang117** [comment]
Related: https://github.com/balena-os/balena-supervisor/pull/949/files (set to defaults with invalid config var)
