### ISSUE TITLE
Log better messages for cloud API error responses

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-supervisor#1680]
A lot of times the API status responses will just log the status code and nothing else. We can provide some more information based on the status code and also dump the headers in case they include useful info.

For example you will see something like:

```
f7402c2  [error]   Error from the API: 401
f7402c2  [error]   Non-200 response from the API! Status code: 401 - message: Error
f7402c2  [error]         at /usr/src/app/dist/app.js:22:554770
f7402c2  [error]       at runMicrotasks (<anonymous>)
f7402c2  [error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
f7402c2  [error]       at async /usr/src/app/dist/app.js:22:554078
f7402c2  [error]       at async /usr/src/app/dist/app.js:22:555600
```

which is not useful.

**Comment by 20k-ultra** [comment]
We can mask the message to say there is an authentication issue and to obtain new API KEYS for the dashboard for example. However, this is a rare case so providing instructions on how to do that isn't necessary yet since I've only seen it happen once.

**Comment by pipex** [comment]
I closed the issue because of the PR but the PR doesn't really cover all cases. So reopened

**Comment by 20k-ultra** [comment]
I think we missed an opportunity on https://github.com/balena-os/balena-supervisor/pull/1692https://github.com/balena-os/balena-supervisor/pull/1692. We should've made https://github.com/balena-os/balena-supervisor/blob/853acae4a8e5b4ef8f67a16fedd1d550611477bb/src/device-state/current-state.ts#L94 log that there was an error updating the current device state. In addition to logging what is in the response's body we should explain what the failure means. For example, a lot of times people think the 503 error is causing their application to not work but that's just the device cannot update the dashboard.

**Comment by 20k-ultra** [comment]
related: https://github.com/balena-os/balena-supervisor/issues/1685

**Comment by 20k-ultra** [comment]
We have merged in https://github.com/balena-os/balena-supervisor/pull/1692 which has added some improvements but I think we can further improve API error messages because the following example is pretty verbose with a lot of unnecessary info

```
Jun 02 14:40:07 203db23 resin-supervisor[4770]: [error]   Error from the API: 503
Jun 02 14:40:07 203db23 resin-supervisor[4770]: [error]   Non-200 response from the API! Status code: 503 - message: Error: "The API cannot handle your re>
Jun 02 14:40:07 203db23 resin-supervisor[4770]: [error]         at /usr/src/app/dist/app.js:22:554753
Jun 02 14:40:07 203db23 resin-supervisor[4770]: [error]       at runMicrotasks (<anonymous>)
Jun 02 14:40:07 203db23 resin-supervisor[4770]: [error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
Jun 02 14:40:07 203db23 resin-supervisor[4770]: [error]       at async /usr/src/app/dist/app.js:22:554042
Jun 02 14:40:07 203db23 resin-supervisor[4770]: [error]       at async /usr/src/app/dist/app.js:22:555620
```

**Comment by cywang117** [comment]
Additionally, sometimes the error message is `Non-200 response from the API! Status code: xxx - message: Error` without anything else. I'm wondering if message-less errors are being sent from the cloud in some instances.

**Comment by 20k-ultra** [comment]
There are a few status codes which an empty body is expected, 500s..504..503..204..304..etc. We could better handle those but it's meh. Removing the stack trace and including why the device wanted to make the call and if it will retry will be more useful.

```
203db23 [error]   Error from the API: 503
203db23 [error]   Device was unable to fetch the latest target state.
203db23 [error]   Non-200 response from the API! Status code: 503 - message: Error: "The API cannot handle your request"
203db23 [error]   Will retry in 5 seconds.
```

**Comment by 20k-ultra** [comment]
following a Go idiomatic error is also an idea that was suggested which will explain what was attempted and why it failed in a single line.

```
error while doing X: failed to do Y: no disk space
```

I think the above example would translate to:

```
203db23 [error]   Unable to fetch latest target state: Network call to cloud API returned 503 - The API cannot handle your request
203db23 [error]   Will retry in 5 seconds
```

If the action does not have a retry attempt then the 2nd log is omitted. The template would be 

```
203db23 [error]   ${action}: ${failure}
```

for network calls it's important to include the status code and body as it could contain an explanation for the status code. Therefore, ${failure} would be `Network call to cloud API returned ${response.status} - ${response.body}`

**Comment by splitice** [comment]
Even the additional information now available isnt particularly helpful. This is something I started seeing today (unsure of start time).

```
[error]   Error from the API: 503
[error]   Non-200 response from the API! Status code: 503 - message: Error: "The API cannot handle your request right now"
[error]         at sendReportPatch (/usr/src/app/dist/app.js:22:643411)
[error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
[error]       at async /usr/src/app/dist/app.js:22:644497
[error]       at async /usr/src/app/dist/app.js:22:645405
[error]   Error from the API: 503
[error]   Non-200 response from the API! Status code: 503 - message: Error: "The API cannot handle your request right now"
[error]         at sendReportPatch (/usr/src/app/dist/app.js:22:643411)
[error]       at runMicrotasks (<anonymous>)
[error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
[error]       at async /usr/src/app/dist/app.js:22:644497
[error]   Error from the API: 503
[error]   Non-200 response from the API! Status code: 503 - message: Error: "The API cannot handle your request right now"
[error]         at sendReportPatch (/usr/src/app/dist/app.js:22:643411)
[error]       at runMicrotasks (<anonymous>)
[error]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
[error]       at async /usr/src/app/dist/app.js:22:644497
```

Also shouldnt balena-cloud be monitored for 503 rate?

**Comment by cywang117** [comment]
@splitice How often have you noticed these logs and when did you start seeing them? balenaCloud is indeed monitored for 503 rate and there haven't been any noticeable increases in 503 in the last 7 days. 503 logging is expected so I wouldn't worry too much about this error message -- from the Supervisor's POV it just means that the Supervisor will retry the last request.

**Comment by splitice** [comment]
@cywang117 Some time between 3 months ago and today. I only check supervisor as part of our release QA process and I would have noticed that during the last QA. Doesnt appear to affect anything other than creating a bunch of Journal entries (potentially flushing out other useful messages, but thats minor).

I can confirm that updating to the latest balena-supervisor has no effect (as expected it's a server side error). We are moving from 12.1.5 to 12.10.10 in this update. Both show similar messages.

I'm not sure what the frequency of these requests are but I see those messages every few minutes.

**Comment by cywang117** [comment]
@splitice We're looking at an improvement to the Supervisor code that will set a backoff timer when it encounters 503 in a response, so that the API isn't repeatedly hammered despite sending 503. This will hopefully reduce the frequency of 503's in the journal logs. 

Another change that's beginner-friendly is to remove the stack trace from being logged (i.e., starting 2nd line with `at sendReportPatch (/usr/src...)` since it doesn't add more clarity and only causes user alarm. It also clogs journal entries, potentially flushing out useful logs as you say. Anyone who sees this, feel free to open a PR ;)

**Comment by 20k-ultra** [comment]
https://github.com/balena-os/balena-supervisor/pull/1798 has made some improvements to current state reporting errors. For example, whenever there was a network issue the Supervisor logged `[event]   Event: Device state report failure {"error":{"message":""}}` but now logs `[event]   Event: Device state report failure {"error":"getaddrinfo ENOTFOUND api.domain.com"}`
