### ISSUE TITLE
Failure to start

### ISSUE THREAD

**Issue by splitice** [balena-os/balena-supervisor#1795]
If supervisor starts before balena engine is healthy (assumed reason balena-engine.sock was not yet available) it will fail to start with:

```
[error]   Firewall mode not applied
[error]   Error applying firewall mode Error: connect ECONNREFUSED /var/run/balena-engine.sock
[error]         at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
[event]   Event: Firewall mode not applied due to error {}
[debug]   Starting api binder
(node:1) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
(node:1) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED /var/run/balena-engine.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

This unhandled rejection causes a stall in the start process.

```
# balena ps
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS                             PORTS               NAMES
[...]
0f77bf7e0289        [...]   "/usr/src/app/entry.…"   6 days ago          Up 58 minutes (health: starting)                       resin_supervisor
```

**Comment by splitice** [comment]
FYI If you are looking for a way to trigger crashes that lead to unexpected starts I recommend `stress-ng --thrash`. Crashing balena engine was not the intention, but it lead to this discovery.

**Comment by cywang117** [comment]
@splitice Thank you for providing reproduction steps! To my knowledge, `stress-ng` is not available in the host OS nor is it a package installed in the Supervisor container. Could you provide more details about how you ran this command?

**Comment by splitice** [comment]
Correct @cywang117 stress-ng has been added to our HostOS builds (for stability testing). It's unexpectedly good at triggering random service crashes (due to memory pressure) and watchdog timeouts.

**Comment by cywang117** [comment]
Thank you @splitice for the tip about `stress-ng`! I'll send this issue to our OS team - if they aren't using this already, I wonder if this would be useful during testing for them.

From the Supervisor's perspective, what could be made better in the case of an unexpected engine crash is to catch this error and log a better error message. [Here](https://github.com/balena-os/balena-supervisor/blob/master/src/supervisor.ts#L36) is where one can start looking, if anyone is interested in making a PR :)

If the engine's condition is bad to the point of not even stopping containers on exit, then there's not much the Supervisor can do, as it does not manage engine condition, but rather interfaces with the engine while assuming its health/uptime.

**Comment by pipex** [comment]
This sounds like it could be an instance of https://github.com/balena-os/balena-supervisor/issues/1231 @splitice @cywang117. The supervisor cannot start before the engine as it is a container running on top of the engine. Another instance where I've observed that type of error is when the engine crashes but the supervisor process has not been killed yet as Christina points out. On that condition I agree the best we could hope for is to improve the logs and terminate early.

Can you reliably replicate this issue? Could you share the conditions where you have seen this?

**Comment by cywang117** [comment]
It sounds like handling UnhandledPromiseRejection at the root level of the process may work, via a `try..catch` in the `init` method of `supervisor.ts` which only catches UnhandledPromiseRejection and exits the process with a user-friendly error message. Maybe also pass the actual error status & message for debugging purposes, but leave out the stack trace if it exists. If so, this sounds like a very good beginner issue for anyone interested as I mentioned above :)

Also, if we migrate Node 16 when it reaches LTS in October 2021, the behavior surrounding unhandled promise rejections will change from warn --> throw (Node 15 is when this behavior changed), so it may be less work to wait until then, in case the error signature changes in some way..
