### ISSUE TITLE
Running a preloaded app without having internet connectivity fails (RPI3 32 bits OS version 2.98.20)

### ISSUE THREAD

**Issue by floion** [balena-os/balena-supervisor#1943]
Trying to run an OS with preloaded wifi connect app, without eth plugged in. The WiFi Connect AP won't show up in the scan list until eth is plugged in and at that same time the board appears online in the dashboard. Then, using the webterminal to check what's going on:

```
Aug 06 14:41:27 b1f4f0b balena-supervisor[2276]: [info]    Attempting to load any preloaded applications
Aug 06 14:41:42 b1f4f0b balena-supervisor[2276]: [error]   LogBackend: unexpected error: Error: getaddrinfo EAI_AGAIN api.balena-cloud.com
Aug 06 14:41:42 b1f4f0b balena-supervisor[2276]: [error]         at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:76:26)
Aug 06 14:41:57 b1f4f0b balena-supervisor[2276]: [debug]   getaddrinfo EAI_AGAIN api.balena-cloud.com
Aug 06 14:41:57 b1f4f0b balena-supervisor[2276]: [event]   Event: Loading preloaded apps failed {"error":{"message":"getaddrinfo EAI_AGAIN api.balena-cloud.com","stack":"Error: getaddrinfo EAI_AGAIN api.balena-cloud.com\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:76:26)"}}
```

**Comment by 20k-ultra** [comment]
Additional logs while reproducing this:

```
root@2d97200:~# journalctl -fn 100 -u balena-supervisor
-- Journal begins at Thu 2022-05-12 16:50:07 UTC. --
May 12 16:50:27 2d97200 balena-supervisor[1539]: Error response from daemon: No such container: resin_supervisor
May 12 16:50:27 2d97200 balena-supervisor[1549]: Error response from daemon: No such container: balena_supervisor
May 12 16:50:27 2d97200 balena-supervisor[1559]: active
May 12 16:50:27 2d97200 balena-supervisor[1578]: Error: No such object: balena_supervisor
May 12 16:50:28 2d97200 balena-supervisor[1619]: find: /mnt/root/tmp/balena-supervisor/services: No such file or directory
May 12 16:50:29 2d97200 balena-supervisor[1619]: [info]    Supervisor v13.1.6 starting up...
May 12 16:50:29 2d97200 balena-supervisor[1619]: [info]    Setting host to discoverable
May 12 16:50:29 2d97200 balena-supervisor[1619]: [warn]    Invalid firewall mode: . Reverting to state: off
May 12 16:50:29 2d97200 balena-supervisor[1619]: [info]    Applying firewall mode: off
May 12 16:50:29 2d97200 balena-supervisor[1619]: [debug]   Performing database cleanup for container log timestamps
May 12 16:50:29 2d97200 balena-supervisor[1619]: [debug]   Starting systemd unit: avahi-daemon.service
May 12 16:50:29 2d97200 balena-supervisor[1619]: [debug]   Starting systemd unit: avahi-daemon.socket
May 12 16:50:29 2d97200 balena-supervisor[1619]: [debug]   Starting logging infrastructure
May 12 16:50:29 2d97200 balena-supervisor[1619]: [info]    Previous engine snapshot was not stored. Skipping cleanup.
May 12 16:50:29 2d97200 balena-supervisor[1619]: [debug]   Handling of local mode switch is completed
May 12 16:50:29 2d97200 balena-supervisor[1619]: [info]    Starting firewall
May 12 16:50:29 2d97200 balena-supervisor[1619]: [success] Firewall mode applied
May 12 16:50:29 2d97200 balena-supervisor[1619]: [debug]   Starting api binder
May 12 16:50:29 2d97200 balena-supervisor[1619]: (node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
May 12 16:50:29 2d97200 balena-supervisor[1619]: [info]    API Binder bound to: https://api.balena-staging.com/v6/
May 12 16:50:29 2d97200 balena-supervisor[1619]: [event]   Event: Supervisor start {}
May 12 16:50:29 2d97200 balena-supervisor[1619]: [debug]   Connectivity check enabled: true
May 12 16:50:29 2d97200 balena-supervisor[1619]: [debug]   Starting periodic check for IP addresses
May 12 16:50:29 2d97200 balena-supervisor[1619]: [info]    VPN connection is not active.
May 12 16:50:29 2d97200 balena-supervisor[1619]: [info]    Waiting for connectivity...
May 12 16:50:29 2d97200 balena-supervisor[1619]: [success] Initialised splash image backend
May 12 16:50:29 2d97200 balena-supervisor[1619]: [info]    Reporting initial state, supervisor version and API info
May 12 16:50:29 2d97200 balena-supervisor[1619]: [info]    Attempting to load any preloaded applications
May 12 16:50:44 2d97200 balena-supervisor[1619]: [error]   LogBackend: unexpected error: Error: getaddrinfo EAI_AGAIN api.balena-staging.com
May 12 16:50:44 2d97200 balena-supervisor[1619]: [error]         at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:76:26)
May 12 16:50:59 2d97200 balena-supervisor[1619]: [debug]   getaddrinfo EAI_AGAIN api.balena-staging.com
May 12 16:50:59 2d97200 balena-supervisor[1619]: [event]   Event: Loading preloaded apps failed {"error":{"message":"getaddrinfo EAI_AGAIN api.balena-staging.com","stack":"Error: getaddrinfo EAI_AGAIN api.balena-staging.com\n    at Ge                        tAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:76:26)"}}
May 12 16:50:59 2d97200 balena-supervisor[1619]: [debug]   Migrated existing apps.json
May 12 16:50:59 2d97200 balena-supervisor[1619]: [info]    Starting API server
May 12 16:50:59 2d97200 balena-supervisor[1619]: [info]    Supervisor API successfully started on port 48484
May 12 16:50:59 2d97200 balena-supervisor[1619]: [debug]   Ensuring device is provisioned
May 12 16:50:59 2d97200 balena-supervisor[1619]: [info]    Reporting initial configuration
May 12 16:51:14 2d97200 balena-supervisor[1619]: [error]   Error reporting initial configuration, will retry Error: getaddrinfo EAI_AGAIN api.balena-staging.com
May 12 16:51:14 2d97200 balena-supervisor[1619]: [error]         at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:76:26)
May 12 16:51:59 2d97200 balena-supervisor[1619]: [error]   Error reporting initial configuration, will retry Error: getaddrinfo EAI_AGAIN api.balena-staging.com
May 12 16:51:59 2d97200 balena-supervisor[1619]: [error]         at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:76:26)
May 12 16:52:44 2d97200 balena-supervisor[1619]: [error]   Error reporting initial configuration, will retry Error: getaddrinfo EAI_AGAIN api.balena-staging.com
May 12 16:52:44 2d97200 balena-supervisor[1619]: [error]         at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:76:26)
```

**Comment by cywang117** [comment]
We found the source of the error.. when preloading, the CLI calls the API's v2 state endpoint to get app information, and v13+ Supervisors query some info from the API to convert this v2 apps data into v3. The long term fix would be for preloading to use the proper state endpoint depending on OS version that's being preloaded to, but for now, I'll make a patch shortly and bump meta-balena.

Right now, devices preloaded without internet that are running >= v13.0.0, <= v13.1.6 will not be able to start up preloaded apps. After the patch, preloaded apps will start but will restart once the device connects to the internet, since the Supervisor will get v3 state endpoint information from the cloud and will change some container env vars (*_APP_UUID) to match the target state.

**Comment by pipex** [comment]
The closed issue fixed a couple of bugs with the old preloading behavior. The actual solution for allowing preloading without internet connectivity was fixed in https://github.com/balena-io/balena-cli/pull/2483. The latest CLI is required so the correct version of target state is used on preloading.
