### ISSUE TITLE
Supervisor doesn't start with legacy image/container still present

### ISSUE THREAD

**Issue by imrehg** [balena-os/balena-supervisor#753]
Had a device that runs now supervisor `v7.19.7`, after an update on a device that used supervisor `v6.6.0`. The supervisor doesn't start up properly afterwards, with this issue.
Device is in a legacy application.

```
-- Logs begin at Fri 2018-10-12 12:15:34 UTC, end at Fri 2018-10-12 12:18:07 UTC. --
Oct 12 12:15:55 fd2eec9 systemd[1]: Starting Resin supervisor...
Oct 12 12:15:55 fd2eec9 balena[1091]: Error response from daemon: No such container: resin_supervisor
Oct 12 12:15:55 fd2eec9 systemctl[1115]: active
Oct 12 12:15:55 fd2eec9 systemd[1]: Started Resin supervisor.
Oct 12 12:15:56 fd2eec9 healthdog[1119]: Error: No such object: resin_supervisor
Oct 12 12:15:57 fd2eec9 healthdog[1119]: Error: No such object: resin_supervisor
Oct 12 12:15:57 fd2eec9 healthdog[1119]: Error: No such container: resin_supervisor
Oct 12 12:16:01 fd2eec9 healthdog[1119]: Starting system message bus: dbus.
Oct 12 12:16:01 fd2eec9 healthdog[1119]:  * Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon
Oct 12 12:16:01 fd2eec9 healthdog[1119]:    ...done.
Oct 12 12:16:13 fd2eec9 healthdog[1119]: [2018-10-12T12:16:13.101Z] Event: Supervisor start {}
Oct 12 12:16:13 fd2eec9 healthdog[1119]: [2018-10-12T12:16:13.254Z] Killing legacy containers
Oct 12 12:16:13 fd2eec9 healthdog[1119]: [2018-10-12T12:16:13.399Z] Unhandled rejection TypeError: Cannot read property 'image' of undefined
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at e.objectNameForLogs (/usr/src/app/dist/app.js:646:78835)
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at e.logSystemEvent (/usr/src/app/dist/app.js:646:77267)
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at /usr/src/app/dist/app.js:646:5869
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at c (/usr/src/app/dist/app.js:9:75656)
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at Function.e.attempt.e.try (/usr/src/app/dist/app.js:320:121777)
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at t.e.exports.t._killContainer (/usr/src/app/dist/app.js:646:5814)
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at t._killContainer (/usr/src/app/dist/app.js:646:3713)
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at /usr/src/app/dist/app.js:646:5213
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at c (/usr/src/app/dist/app.js:9:75656)
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at f._promiseFulfilled (/usr/src/app/dist/app.js:320:134630)
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at f.s._iterate (/usr/src/app/dist/app.js:320:103627)
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at f.t (/usr/src/app/dist/app.js:320:102848)
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at A._settlePromise (/usr/src/app/dist/app.js:320:93872)
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at A._settlePromise0 (/usr/src/app/dist/app.js:320:94533)
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at A._settlePromises (/usr/src/app/dist/app.js:320:95885)
Oct 12 12:16:13 fd2eec9 healthdog[1119]:     at f (/usr/src/app/dist/app.js:320:97479)
Oct 12 12:17:41 fd2eec9 systemd[1]: Stopping Resin supervisor...
Oct 12 12:17:52 fd2eec9 balena[1323]: resin_supervisor
Oct 12 12:17:52 fd2eec9 systemd[1]: Stopped Resin supervisor.
Oct 12 12:17:53 fd2eec9 systemd[1]: Starting Resin supervisor...
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_eblf)

**Comment by cywang117** [comment]
Closing as these are legacy Supervisors, and we no longer allow legacy applications to be created through balenaCloud. Please reopen with logs & Supervisor source / target versions if encountered again.
